const fs = require('fs');
const c = fs.readFileSync('src/App.js', 'utf8');

const oldJSX = `            <button className="news-modal-close" onClick={() => setOpenNewsPost(null)} aria-label="Fechar">×</button>\r\n            {(openNewsPost.mediaKind === 'video' || openNewsPost.mediaKind === 'video_vertical') && openNewsPost.mediaUrl ? (\r\n              openNewsPost.mediaUrl.includes('instagram.com') ? (\r\n                <a className="news-modal-external" href={openNewsPost.mediaUrl} target="_blank" rel="noreferrer">\r\n                  <span>&#9654;</span> Assistir no Instagram\r\n                </a>\r\n              ) : (\r\n              <div className="news-modal-video">\r\n                <iframe\r\n                  src={(() => { try { const u = new URL(openNewsPost.mediaUrl); const id = u.searchParams.get('v') || (u.hostname === 'youtu.be' ? u.pathname.slice(1) : u.pathname.split('/shorts/')[1]?.split('?')[0] || u.pathname.split('/embed/')[1]?.split('/')[0] || u.pathname.slice(1)); return id ? \`https://www.youtube-nocookie.com/embed/\${id}\` : openNewsPost.mediaUrl; } catch { return openNewsPost.mediaUrl; } })()}\r\n                  title={openNewsPost.title}\r\n                  frameBorder="0"\r\n                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"\r\n                  allowFullScreen\r\n                />\r\n              </div>\r\n              )\r\n            ) : openNewsPost.image ? (\r\n              <img className="news-modal-img" src={openNewsPost.image} alt="" />\r\n            ) : null}\r\n            <div className="news-modal-body">`;

const newJSX = `            <button className="news-modal-close" onClick={() => setOpenNewsPost(null)} aria-label="Fechar">×</button>\r\n            <div className="news-modal-inner">\r\n            {(openNewsPost.mediaKind === 'video' || openNewsPost.mediaKind === 'video_vertical') && openNewsPost.mediaUrl ? (\r\n              openNewsPost.mediaUrl.includes('instagram.com') ? (\r\n                <a className="news-modal-external" href={openNewsPost.mediaUrl} target="_blank" rel="noreferrer">\r\n                  <span>&#9654;</span> Assistir no Instagram\r\n                </a>\r\n              ) : (\r\n              <div className="news-modal-video">\r\n                <iframe\r\n                  src={(() => { try { const u = new URL(openNewsPost.mediaUrl); const id = u.searchParams.get('v') || (u.hostname === 'youtu.be' ? u.pathname.slice(1) : u.pathname.split('/shorts/')[1]?.split('?')[0] || u.pathname.split('/embed/')[1]?.split('/')[0] || u.pathname.slice(1)); return id ? \`https://www.youtube-nocookie.com/embed/\${id}\` : openNewsPost.mediaUrl; } catch { return openNewsPost.mediaUrl; } })()}\r\n                  title={openNewsPost.title}\r\n                  frameBorder="0"\r\n                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"\r\n                  allowFullScreen\r\n                />\r\n              </div>\r\n              )\r\n            ) : openNewsPost.image ? (\r\n              <img className="news-modal-img" src={openNewsPost.image} alt="" />\r\n            ) : null}\r\n            <div className="news-modal-body">`;

if (!c.includes(oldJSX)) { console.error('JSX BLOCK NOT FOUND'); process.exit(1); }
fs.writeFileSync('src/App.js', c.replace(oldJSX, newJSX));
console.log('OK');
