const fs = require('fs');
let c = fs.readFileSync('src/PaginasAdmin.js', 'utf8');

// 1. List items: add thumb
const oldList = `              <button\r\n                key={s.key}\r\n                type="button"\r\n                className={\`admin-list-item \${selectedSection === s.key ? 'is-active' : ''}\`}\r\n                onClick={() => setSelectedSection(s.key)}\r\n              >\r\n                <div className="admin-list-item-title">{s.label}</div>\r\n                <div className="admin-list-item-meta">\r\n                  <span>{config.backgroundsBySection?.[s.key]?.imageUrl ? 'com imagem' : 'sem imagem'}</span>\r\n                </div>\r\n              </button>`;

const newList = `              <button\r\n                key={s.key}\r\n                type="button"\r\n                className={\`admin-list-item admin-list-item--thumb \${selectedSection === s.key ? 'is-active' : ''}\`}\r\n                onClick={() => setSelectedSection(s.key)}\r\n              >\r\n                <div className="admin-list-item-img">\r\n                  {config.backgroundsBySection?.[s.key]?.imageUrl\r\n                    ? <img src={config.backgroundsBySection[s.key].imageUrl} alt="" />\r\n                    : <div className="admin-list-item-img-empty" />}\r\n                </div>\r\n                <div className="admin-list-item-info">\r\n                  <div className="admin-list-item-title">{s.label}</div>\r\n                  <div className="admin-list-item-meta">\r\n                    <span>{config.backgroundsBySection?.[s.key]?.imageUrl ? 'com imagem' : 'sem imagem'}</span>\r\n                  </div>\r\n                </div>\r\n              </button>`;

if (!c.includes(oldList)) { console.error('LIST NOT FOUND'); process.exit(1); }
c = c.replace(oldList, newList);

// 2. Replace preview box with real site preview (uses same CSS vars as App.js)
const oldPreviewBox = `              <div className="admin-pages-preview-box admin-pages-preview-box-lg" style={previewStyle}>\r\n                <div className="admin-pages-preview-overlay" />\r\n                <div className="admin-pages-preview-content">\r\n                  <div className="admin-pages-preview-h1">MIND OF A</div>\r\n                  <div className="admin-pages-preview-h1">DEAD BODY</div>\r\n                  <div className="admin-pages-preview-chip">{sectionLabel}</div>\r\n                </div>\r\n              </div>\r\n\r\n              {selectedSection === 'sobre' ? (\r\n                <div className="admin-card" style={{ marginTop: 14 }}>\r\n                  <div className="admin-panel-title" style={{ fontSize: 14, letterSpacing: 2 }}>SOBRE — CONTEÚDO</div>\r\n                  <div className="admin-pages-divider" />\r\n\r\n                  <div className="admin-field-row" style={{ display: 'flex', gap: 10, alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap' }}>\r\n                    <div className="admin-muted">Edite título/texto (PT/EN) e imagem da seção Sobre.</div>\r\n                    <button type="button" className="admin-btn admin-btn-primary" onClick={openEditor}>\r\n                      EDITAR\r\n                    </button>\r\n                  </div>\r\n                </div>\r\n              ) : null}\r\n\r\n              <div style={{ display: 'flex', gap: 10, marginTop: 14, flexWrap: 'wrap', justifyContent: 'flex-end' }}>\r\n                <button type="button" className="admin-btn admin-btn-ghost" onClick={resetSelected} disabled={saving || loading}>\r\n                  RESETAR SEÇÃO\r\n                </button>\r\n                <button type="button" className="admin-btn admin-btn-primary" onClick={openEditor}>\r\n                  EDITAR\r\n                </button>\r\n              </div>`;

const newPreviewBox = `              <div className="admin-pages-site-preview" style={previewStyle}>\r\n                <div className="admin-pages-site-preview-img" />\r\n                <div className="admin-pages-site-preview-nav">\r\n                  <div className="admin-pages-site-preview-logo" />\r\n                  <div className="admin-pages-site-preview-links">\r\n                    {['INÍCIO','SOBRE','NOTÍCIAS','DISCOGRAFIA','LOJA','CONTATO'].map(l => <span key={l}>{l}</span>)}\r\n                  </div>\r\n                </div>\r\n                <div className="admin-pages-site-preview-body">\r\n                  <div className="admin-pages-site-preview-title">MIND OF A DEAD BODY</div>\r\n                  <div className="admin-pages-site-preview-section">{sectionLabel}</div>\r\n                </div>\r\n              </div>\r\n\r\n              <div style={{ display: 'flex', gap: 10, marginTop: 14, justifyContent: 'flex-end' }}>\r\n                <button type="button" className="admin-btn admin-btn-primary" onClick={openEditor}>EDITAR</button>\r\n              </div>`;

if (!c.includes(oldPreviewBox)) { console.error('PREVIEW BOX NOT FOUND'); process.exit(1); }
c = c.replace(oldPreviewBox, newPreviewBox);

// 3. Add RESETAR to editor bottom buttons (next to FECHAR)
const oldEditorBtns = `                <button type="button" className="admin-btn" onClick={closeEditor}>\r\n                  FECHAR\r\n                </button>\r\n                <button type="button" className="admin-btn admin-btn-primary" onClick={applyDraft}>\r\n                  APLICAR\r\n                </button>`;

const newEditorBtns = `                <button type="button" className="admin-btn admin-btn-ghost" onClick={resetSelected} disabled={saving || loading}>\r\n                  RESETAR SEÇÃO\r\n                </button>\r\n                <button type="button" className="admin-btn" onClick={closeEditor}>\r\n                  FECHAR\r\n                </button>\r\n                <button type="button" className="admin-btn admin-btn-primary" onClick={applyDraft}>\r\n                  APLICAR\r\n                </button>`;

if (!c.includes(oldEditorBtns)) { console.error('EDITOR BTNS NOT FOUND'); process.exit(1); }
c = c.replace(oldEditorBtns, newEditorBtns);

fs.writeFileSync('src/PaginasAdmin.js', c);
console.log('OK');
